spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo_manager?useSSL=false&serverTimezone=UTC
    username: root
    password: 5457hzcx
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
