spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo_manager?useSSL=false&serverTimezone=UTC
    username: root
    password: 5457hzcx
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  security:
    enabled: false  # 这里应该用 `enabled: false`
file:
  upload-dir: ./uploads  # 使用相对路径，这里定义为项目根目录下的 "uploads" 文件夹
# application.yml
server:
  port: 8081